title: "TalkRush"
description: "Chat with strangers and make new friends in free random chat rooms. Enjoy anonymous text & video chat, group chat rooms. Safe Omegle & OmeTV alternative."
baseurl: "" 
url: "https://shkumaraman.github.io"

# Language and region
lang: "en"
locale: "en_IN"

# Default Open Graph
image: "/assets/chat.png"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
